# generated by ChatGPT 5/21

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

GT = 3 / 2

# === Define the function you want to plot ===
def f(x, y):
    # return np.sin(x) + np.cos(y)
    # return (0.1 * x**4) + x**3 + (0.2 * y**2)
    # return (1 - x)**2 + 100 * (y - x**2)**2
    return (1.5 - x + x*y)**2 + (2.25 - x + x*y**2)**2 + (2.625 - x + x*y**3)**2

# === Load (x, y) points from file ===
def load_path(filename):
    data = np.loadtxt(filename)
    x = data[:, 0]
    y = data[:, 1]
    z = f(x, y)
    return x, y, z

# === Main plotting function ===
def plot_surface_with_path(path_file, save_file=""):
    # Load path
    path_x, path_y, path_z = load_path(path_file)

    # center of graph
    avg_x = np.mean(path_x)
    avg_y = np.mean(path_y)
    avg_z = np.mean(path_z)
    xydev = np.max(abs(path_x - avg_x))
    xydev = max(xydev, np.max(path_y - avg_y))
    xydev = xydev * GT
    zdev  = np.max(abs(path_z - avg_z))
    zdev  = zdev * GT

    # Create surface mesh
    # x_range = np.linspace(avg_x - xydev, avg_x + xydev, 50)
    # y_range = np.linspace(avg_y - xydev, avg_y + xydev, 50)
    # X, Y = np.meshgrid(x_range, y_range)
    # Z = f(X, Y)
    # Z = np.where((Z < avg_z - zdev) | (Z > avg_z + zdev), np.nan, Z) 
    # get surface mesh
    x_range = np.linspace(-1.46678415, 6.216204749999999, 50)
    y_range = np.linspace(-3.7098825, 3.9731064, 50)
    X, Y = np.meshgrid(x_range, y_range)
    Z = f(X, Y)
    Z = np.where((Z < -28.838043307735568) | (Z > 34.79935866154711), np.nan, Z) 

    # Plotting
    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection='3d')

    # Surface plot
    ax.plot_surface(X, Y, Z, cmap='viridis', alpha=0.7, edgecolor='none', antialiased=False)

    # Path plot
    ax.plot(path_x, path_y, path_z, color='red', linewidth=2, marker='o', label='Descent Path')

    # print graph range
    print(f'X: {avg_x - xydev}, {avg_x + xydev}')  
    print(f'Y: {avg_y - xydev}, {avg_y + xydev}')
    print(f'Z: {avg_z -  zdev}, {avg_z +  zdev}')

    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('f(x, y)')
    ax.set_title('Gradient Descent Path')
    ax.legend()
    plt.tight_layout()

    if save_file=="":
        plt.show()
    else:
        ax.view_init(elev=90, azim=-90)
        plt.savefig(sys.argv[2], dpi=150)

# === Example usage ===
# Save this as `plot_path.py`, then run:
# python plot_path.py path.txt
if __name__ == "__main__":
    import sys
    if len(sys.argv) == 2:
        plot_surface_with_path(sys.argv[1])
    elif len(sys.argv) == 3:
        plot_surface_with_path(sys.argv[1], sys.argv[2])
    else:
        print("... debug_file.txt save_file.png")